############################################################
#
# Notify Graeme if there is a delay on the morning commute
#
############################################################

- alias: NOTIFY Graeme if MORNING commute is DELAYED
  trigger:
    platform: numeric_state
    entity_id: sensor.graeme_to_work
    above: 56
#  condition:
#    condition: and
#    conditions:
#    - condition: time
#      after: '06:00:00'
#      before: '08:00:00'
#      weekday:
#      - mon
#      - tue
#      - wed
#      - thu
#      - fri
#    - condition: state
#      entity_id: device_tracker.iphone
#      state: 'home'
  action:
    - service: notify.notify_graeme
      data:
        message: >
          Commute time of {{ states("sensor.graeme_to_work") }} minutes

############################################################
#
# Notify Graeme if there is a delay on the evening commute
#
############################################################

- alias: NOTIFY Graeme if EVENING commute is DELAYED
  trigger:
    platform: numeric_state
    entity_id: sensor.graeme_to_home
    above: 56
  condition:
    condition: and
    conditions:
    - condition: time
      after: '15:30:00'
      before: '17:30:00'
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: device_tracker.iphone
      state: !secret zone1_name
  action:
    - service: notify.notify_graeme
      data_template:
        message: >
          Commute time of {{ states("sensor.graeme_to_home") }} minutes

