############################################################
#
# Heal Z-Wave Network on Startup
#
############################################################

- alias: Heal Z-Wave Network on Startup
  trigger:
      platform: event
      event_type: homeassistant_start
  action:
    service: zwave.heal_network 
