############################################################
#
# Turn on lights when Visitor Mode is On
#
############################################################

- alias: Turn ON lights when Visitor Mode button is ON
  trigger:
    platform: state
    entity_id: input_boolean.visitor 
    state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: 
        - group.visitor_lights
    - service: homeassistant.turn_off
      entity_id:
        - automation.turn_on_back_lights_when_pir_channel_is_activated
        - automation.turn_on_courtyard_lights_when_pir_channel_is_activated
          
############################################################
#
# Turn off lights when Visitor Button is Off
#
############################################################

- alias: Turn OFF lights when Panic Button is OFF
  trigger:
    platform: state
    entity_id: input_boolean.visitor
    state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - group.visitor_lights
    - service: homeassistant.turn_on
      entity_id:
        - automation.turn_on_back_lights_when_pir_channel_is_activated
        - automation.turn_on_courtyard_lights_when_pir_channel_is_activated
