############################################################
#
# Home Assistant Automation View
#
############################################################

Automation:
  name: Automation
  view: yes
  entities:
    - group.automations

Automations:
  - automation.backup_configuration_at_3am
  - automation.flash_hue_go_when_doorbell_at_door_is_pressed
  - automation.flash_hue_go_when_doorbell_at_gate_is_pressed
  - automation.hall_light_on_when_motion_is_active
  - automation.kitchen_strip_light_on_when_motion_is_active
  - automation.notify_aileen_when_washine_machine_is_finished
  - automation.notify_all_when_steriliser_power_is_high
  - automation.notify_all_when_steriliser_power_is_low
  - automation.notify_graeme_if_evening_commute_is_delayed
  - automation.notify_graeme_if_morning_commute_is_delayed
  - automation.notify_graeme_when_update_is_available
  - automation.notify_rasplex_when_courtyard_pir_channel_is_activated
  - automation.notify_rasplex_when_driveway_pir_channel_is_activated
  - automation.notify_rasplex_when_front_pir_channel_is_activated
  - automation.notify_when_electricity_supply_voltage_is_high
  - automation.notify_when_electricity_supply_voltage_is_low
  - automation.porch_light_on_when_motion_is_active
  - automation.set_cctv_detection_to_off_when_front_door_open
  - automation.set_cctv_detection_to_on_when_front_door_closed
  - automation.set_nest_to_away_if_front_door_is_open_for_3_minutes
  - automation.set_nest_to_home_if_front_door_is_closed
  - automation.stairs_light_on_when_lower_motion_is_active
  - automation.stairs_light_on_when_upper_motion_is_active
  - automation.turn_off_lights_when_panic_button_is_off
  - automation.turn_on_back_lights_when_pir_channel_is_activated
  - automation.turn_on_courtyard_lights_when_pir_channel_is_activated
  - automation.turn_on_front_lights_when_front_door_is_opened
  - automation.turn_on_front_lights_when_pir_channel_is_activated
  - automation.turn_on_lights_when_panic_button_is_on
  - automation.turn_on_summer_house_lights_when_pir_channel_is_activated
