############################################################
#
# Home Assistant Camera Configuration
#
############################################################

- platform: mjpeg
  mjpeg_url: !secret camera_mjpeg_url
  name: CCTV Front

#- platform: generic
#  name: People
#  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.iphone.attributes.latitude }},{{ states.device_tracker.iphone.attributes.longitude }}&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:G%7C{{ states.device_tracker.iphone.attributes.latitude }},{{ states.device_tracker.iphone.attributes.longitude }}&markers=color:blue%7Clabel:A%7C{{ states.device_tracker.aileensiphone.attributes.latitude }},{{ states.device_tracker.aileensiphone.attributes.longitude }}
#  limit_refetch_to_url_change: true

#- platform: generic
#  name: Aileen
#  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.aileensiphone.attributes.latitude }},{{ states.device_tracker.aileensiphone.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:A%7C{{ states.device_tracker.aileensiphone.attributes.latitude }},{{ states.device_tracker.aileensiphone.attributes.longitude }}
#  limit_refetch_to_url_change: true
