- platform: kodi
  name: rasplex
  host: !secret rasplex_host
  port: !secret rasplex_port

- platform: twilio_sms
  name: twilio_sms
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token
  from_number: !secret twilio_from_number

- platform: smtp
  name: as_email
  server: !secret smtp_server
  port: !secret smtp_port
  sender: !secret smtp_sender
  recipient: !secret as_email

- platform: smtp
  name: gs_email
  server: !secret smtp_server
  port: !secret smtp_port
  sender: !secret smtp_sender
  recipient: !secret gs_email

- platform: html5
  name: HTML5
  gcm_api_key: !secret gcm_api_key
  gcm_sender_id: !secret gcm_sender_id

- platform: group
  name: as_sms
  services:
    - service: twilio_sms
      data:
        target: !secret aileen_twilio

- platform: group
  name: gs_sms
  services:
    - service: twilio_sms
      data:
        target: !secret graeme_twilio
  
- platform: group
  name: notify_aileen
  services:
    - service: as_sms
    - service: as_email

- platform: group
  name: notify_graeme 
  services:
    - service: gs_sms
    - service: gs_email

- platform: group
  name: notify_all
  services:
    - service: notify_aileen
    - service: notify_graeme
    - service: html5
    - service: rasplex
